---
name: Polycom-Config-File
version: 0.03
author: ["Zachary Blair <zblair@cpan.org>"]
abstract: 'Parse config files for Polycom VoIP phones'
license: perl
distribution_type: module
resources:
  license: http://dev.perl.org/licenses/
requires:
  Encode: 0
  File::Spec: 0
  IO::File: 0
  Test::More: 0
  XML::Twig: 0
  perl: 5.8
provides:
  Polycom::Config::File:
    file: lib/Polycom/Config/File.pm
    version: 0.03
keywords:
  - Polycom
  - VoIP
  - Config
  - SoundPoint
  - SoundStation
  - VVX
